FROM arm32v7/python:3.7.2-slim

LABEL maintainers="dirtycajunrice,circa10a,tkdeviant"

WORKDIR /app

COPY /qemu-arm-static /usr/bin/qemu-arm-static

COPY /requirements.txt /setup.py /ouroboros /README.md /app/

COPY /pyouroboros /app/pyouroboros

RUN pip install --no-cache-dir .

ENTRYPOINT ["ouroboros"]