FROM arm32v6/python:3.7.2-alpine

LABEL maintainers="dirtycajunrice,circa10a,tkdeviant"

COPY / /app

COPY /tmp/qemu-arm-static /usr/bin/qemu-arm-static

WORKDIR /app

RUN apk add --no-cache tzdata && \
    pip install --no-cache-dir .

ENTRYPOINT ["ouroboros"]