FROM arm32v7/python:3.7.2-slim

LABEL maintainers="dirtycajunrice,circa10a,tkdeviant"

COPY / /app

WORKDIR /app

RUN apt-get install tzdata && \
    pip install --no-cache-dir .

ENTRYPOINT ["ouroboros"]