FROM arm64v8/python:3.7.2-alpine

LABEL maintainers="dirtycajunrice,circa10a,tkdeviant"

COPY / /app

COPY /tmp/qemu-aarch64-static /usr/bin/qemu-aarch64-static

WORKDIR /app

RUN apk add --no-cache tzdata && \
    pip install --no-cache-dir .

ENTRYPOINT ["ouroboros"]