FROM arm64v8/python:3.7.2-alpine

LABEL maintainers="dirtycajunrice,circa10a,tkdeviant"

WORKDIR /app

COPY /qemu-aarch64-static /usr/bin/qemu-aarch64-static

COPY /requirements.txt /setup.py /ouroboros /README.md /app/

COPY /pyouroboros /app/pyouroboros

RUN apk add --no-cache tzdata && \
    pip install --no-cache-dir .

ENTRYPOINT ["ouroboros"]