FROM arm32v7/python:3.7.2-slim

LABEL maintainers="dirtycajunrice,circa10a,tkdeviant"

COPY / /app

COPY /tmp/qemu-arm-static /usr/bin/qemu-arm-static

WORKDIR /app

RUN pip install --no-cache-dir .

ENTRYPOINT ["ouroboros"]